Use newer flake8 to run on ubuntu-focal Zuul machines
flake8 3.6.0  fails on ubuntu-focal zuul machines running python3.8
with the following error:
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

The update removes the version constraint to use newer flake8.  This
also ignores new warnings/errors, which should be addressed in a
future update to remove the ignores

Change-Id: Id22fb14e2cce76c2f4f5234abb3be4db68c70555
Partial-Bug: 1895054
Signed-off-by: Steven Webster <steven.webster@windriver.com>