CentOS 8: Fix openstack-tox-pep8 stx-integ-pylint
fix Zuul error stx-integ-pylint->
Consider explicitly re-raising using the
'from' keyword (raise-missing-from)

openstack-tox-pep8->
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

Change-Id: I9dd73658303e7d3906db083d3de21442e94a7d24
Signed-off-by: Yong Fu <fuyong@neusoft.com>