containerd: upgrade Build-Depends to Golang 1.17
The Build-Depends package "golang-github-containernetworking-plugins"
has been upgraded to 1.2.0 by https://review.opendev.org/c/starlingx/integ/+/878722,
that causes a build issue of containerd:

=====================
src/github.com/containernetworking/plugins/vendor/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
src/github.com/containernetworking/plugins/vendor/golang.org/x/sys/unix/syscall_linux.go:2270:9: undefined: unsafe.Slice
src/github.com/containernetworking/plugins/vendor/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
src/github.com/containernetworking/plugins/vendor/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
=====================

The "unsafe.Slice" is introduced since Golong 1.17, so change the Build-Depends.

Test Plan:
- PASS: build-pkgs -a -c
- PASS: build-image

Closes-Bug: 2016936

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>
Change-Id: Ic14ef5f273e5d6b5deb2de00f74d3b823bd198ad