Revert "integ: gpu-operator helm charts"
This reverts commit 41bdf53f65684b54abaa3098a5fe3acf568cdf2a.

Reason for revert: gpu operator patch is breaking stx-master build.

e.g.,
08:06:44 Failed to build packages:  gpu-operator-1.6.0-0.tis.1.src.rpm; problem with:
Patch #2 (enablement-support-on-starlingx-cloud-platform.patch):
. .
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file deployments/gpu-operator/templates/operator.yaml.rej
patching file deployments/gpu-operator/values.yaml
error: Bad exit status from /var/tmp/rpm-tmp.VQuqLh (%prep)

Change-Id: Id7a05987586582c940d605874d1e0f813333f2c3