Disable isolcpu-device-plugin debug package
Disable the building of a debug package for isolcpus-device-plugin. It
causes grief with regards to centos8. As seen below:

RPM build errors:
error: Empty %files file /builddir/build/BUILD/isolcpus-device-plugin-1.0/debugsourcefiles.list
    line 23: second Summary
    Empty %files file /builddir/build/BUILD/isolcpus-device-plugin-1.0/debugsourcefiles.list
Child return code was: 1

Story: 2006796
Task: 42945

Signed-off-by: Charles Short <charles.short@windriver.com>
Change-Id: Ia239704de1b08909f2ef84d4aadd1fe240bf1e75